//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_sislogik.WS_SendEmpData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_SendEmpData.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmldata del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmpData", ReplyAction="*")]
        Test_sislogik.WS_SendEmpData.SendEmpDataResponse SendEmpData(Test_sislogik.WS_SendEmpData.SendEmpDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmpData", ReplyAction="*")]
        System.Threading.Tasks.Task<Test_sislogik.WS_SendEmpData.SendEmpDataResponse> SendEmpDataAsync(Test_sislogik.WS_SendEmpData.SendEmpDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmpDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmpData", Namespace="http://tempuri.org/", Order=0)]
        public Test_sislogik.WS_SendEmpData.SendEmpDataRequestBody Body;
        
        public SendEmpDataRequest() {
        }
        
        public SendEmpDataRequest(Test_sislogik.WS_SendEmpData.SendEmpDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmpDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmldata;
        
        public SendEmpDataRequestBody() {
        }
        
        public SendEmpDataRequestBody(string xmldata) {
            this.xmldata = xmldata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmpDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmpDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test_sislogik.WS_SendEmpData.SendEmpDataResponseBody Body;
        
        public SendEmpDataResponse() {
        }
        
        public SendEmpDataResponse(Test_sislogik.WS_SendEmpData.SendEmpDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmpDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmpDataResult;
        
        public SendEmpDataResponseBody() {
        }
        
        public SendEmpDataResponseBody(string SendEmpDataResult) {
            this.SendEmpDataResult = SendEmpDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Test_sislogik.WS_SendEmpData.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Test_sislogik.WS_SendEmpData.WebService1Soap>, Test_sislogik.WS_SendEmpData.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test_sislogik.WS_SendEmpData.SendEmpDataResponse Test_sislogik.WS_SendEmpData.WebService1Soap.SendEmpData(Test_sislogik.WS_SendEmpData.SendEmpDataRequest request) {
            return base.Channel.SendEmpData(request);
        }
        
        public string SendEmpData(string xmldata) {
            Test_sislogik.WS_SendEmpData.SendEmpDataRequest inValue = new Test_sislogik.WS_SendEmpData.SendEmpDataRequest();
            inValue.Body = new Test_sislogik.WS_SendEmpData.SendEmpDataRequestBody();
            inValue.Body.xmldata = xmldata;
            Test_sislogik.WS_SendEmpData.SendEmpDataResponse retVal = ((Test_sislogik.WS_SendEmpData.WebService1Soap)(this)).SendEmpData(inValue);
            return retVal.Body.SendEmpDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test_sislogik.WS_SendEmpData.SendEmpDataResponse> Test_sislogik.WS_SendEmpData.WebService1Soap.SendEmpDataAsync(Test_sislogik.WS_SendEmpData.SendEmpDataRequest request) {
            return base.Channel.SendEmpDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test_sislogik.WS_SendEmpData.SendEmpDataResponse> SendEmpDataAsync(string xmldata) {
            Test_sislogik.WS_SendEmpData.SendEmpDataRequest inValue = new Test_sislogik.WS_SendEmpData.SendEmpDataRequest();
            inValue.Body = new Test_sislogik.WS_SendEmpData.SendEmpDataRequestBody();
            inValue.Body.xmldata = xmldata;
            return ((Test_sislogik.WS_SendEmpData.WebService1Soap)(this)).SendEmpDataAsync(inValue);
        }
    }
}
